#!/usr/bin/env sh
set -eu

exec 2>&1
#source /env

OPTS=""

daemon=sshd
command="/usr/sbin/$daemon"
pidfile="/run/$daemon.pid"

# generate host keys if they don't already exist
ssh-keygen -A >/dev/null 2>&1

# Check if command is executable or not
test -x ${command} || exit 0

#trap "pkill -SIGHUP runsvdir" SIGTERM SIGINT

echo "Starting '${command}' with PID: $$"

exec ${command} -D $OPTS 2>&1
