#!/usr/bin/env sh
set -eu

exec 2>&1
#source /env

: ${cfgfile:="/etc/rsyncd.conf"}

RSYNC_OPTS=""

daemon=rsyncd
command="/usr/bin/rsync"

pidfile="/run/$daemon.pid"

# Check if command is executable or not
test -x ${command} || exit 0

#trap "pkill -SIGHUP runsvdir" SIGTERM SIGINT

echo "Starting '${command}' with PID: $$"

exec ${command} --daemon --no-detach --config=$cfgfile
